version: "3.2"
services:
  bortli-lb:
    build:
      context: bortli
      dockerfile: Dockerfile
    volumes:
      - ./bortli/nginx.conf:/etc/nginx/nginx.conf
      - ./bortli/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080