version: "3.2"
services:
  bortli-lb:
    build:
      context: bortli
      dockerfile: Dockerfile
    volumes:
      - ./bortli/nginx.conf:/etc/nginx/nginx.conf
      - ./bortli/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
  logrotate-lb:
    build:
      context: logrotate
      dockerfile: Dockerfile
    volumes:
      - ./logrotate/nginx.conf:/etc/nginx/nginx.conf
      - ./logrotate/default.conf:/etc/nginx/conf.d/default.conf
      - ./logrotate/html:/usr/share/nginx/html  # 새로운 볼륨 추가
      - ./logrotate/log:/var/log/nginx
    ports:
      - 8080:8080