version: "3.2"
services:
  health-check-lb:
    build:
      context: healthCheck
      dockerfile: Dockerfile
    volumes:
      - ./healthCheck/nginx.conf:/etc/nginx/nginx.conf
      - ./healthCheck/default.conf:/etc/nginx/conf.d/default.conf
      - ./healthCheck/html:/usr/share/nginx/html
    ports:
      - 8080:8080
  brotli-lb:
    build:
      context: brotli
      dockerfile: Dockerfile
    volumes:
      - ./brotli/nginx.conf:/etc/nginx/nginx.conf
      - ./brotli/default.conf:/etc/nginx/conf.d/default.conf
      - ./brotli/html:/usr/share/nginx/html
    ports:
      - 8081:8080
  zstd-lb:
    build:
      context: zstd
      dockerfile: Dockerfile
    volumes:
      - ./zstd/nginx.conf:/etc/nginx/nginx.conf
      - ./zstd/default.conf:/etc/nginx/conf.d/default.conf
      - ./zstd/html:/usr/share/nginx/html
    ports:
      - 8083:8080
  logrotate-lb:
    build:
      context: logrotate
      dockerfile: Dockerfile
    volumes:
      - ./logrotate/nginx.conf:/etc/nginx/nginx.conf
      - ./logrotate/default.conf:/etc/nginx/conf.d/default.conf
      - ./logrotate/html:/usr/share/nginx/html
      - ./logrotate/log:/var/log/nginx
    ports:
      - 8082:8080